name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: just ci && just msrv
